<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20230330022023 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SEQUENCE abono_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE alumno_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE avion_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE cuenta_corriente_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE curso_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE gasto_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE hangar_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE historial_lista_precio_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE instructor_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE instructor_vuelo_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE lista_precio_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE movimiento_cuenta_vuelo_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE movimiento_stock_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE nota_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE piloto_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE producto_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE producto_venta_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE producto_vuelo_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE reserva_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE reserva_hangar_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE reserva_vuelo_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE servicio_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE socio_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE tesorero_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE unidades_pago_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE venta_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE vuelo_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE vuelo_motor_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE vuelo_planeador_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE TABLE abono (id INT NOT NULL, tesorero_id_id INT DEFAULT NULL, socio_id_id INT DEFAULT NULL, piloto_id_id INT DEFAULT NULL, valor INT NOT NULL, fecha DATE NOT NULL, aprobado BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_96A720959221F5E9 ON abono (tesorero_id_id)');
        $this->addSql('CREATE INDEX IDX_96A72095BFA13376 ON abono (socio_id_id)');
        $this->addSql('CREATE INDEX IDX_96A720952D5D35A3 ON abono (piloto_id_id)');
        $this->addSql('CREATE TABLE alumno (id INT NOT NULL, habilitado_por_instructor_id_id INT DEFAULT NULL, habilitado_por_tesorero_id_id INT DEFAULT NULL, dni VARCHAR(50) NOT NULL, nombre VARCHAR(255) NOT NULL, apellido VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, telefono VARCHAR(255) NOT NULL, domicilio TEXT NOT NULL, ciudad VARCHAR(255) NOT NULL, habilitado_volar BOOLEAN NOT NULL, fecha_vencimiento_licencia_medica TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_1435D52DDB969FD1 ON alumno (habilitado_por_instructor_id_id)');
        $this->addSql('CREATE INDEX IDX_1435D52DE3767AC7 ON alumno (habilitado_por_tesorero_id_id)');
        $this->addSql('CREATE TABLE avion (id INT NOT NULL, matricula VARCHAR(255) NOT NULL, fecha_inspeccion DATE NOT NULL, fecha_mantenimiento DATE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE cuenta_corriente (id INT NOT NULL, movimiento_cuenta_vuelo_id_id INT DEFAULT NULL, lista_precio_id_id INT NOT NULL, abono_id_id INT NOT NULL, venta_id_id INT DEFAULT NULL, servicio_id_id INT NOT NULL, reserva_hangar_id_id INT DEFAULT NULL, fecha TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, deuda_remanente INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_36ABB0A744C354F3 ON cuenta_corriente (movimiento_cuenta_vuelo_id_id)');
        $this->addSql('CREATE INDEX IDX_36ABB0A7ED1CD59C ON cuenta_corriente (lista_precio_id_id)');
        $this->addSql('CREATE INDEX IDX_36ABB0A750343FC1 ON cuenta_corriente (abono_id_id)');
        $this->addSql('CREATE INDEX IDX_36ABB0A79F1AB70D ON cuenta_corriente (venta_id_id)');
        $this->addSql('CREATE INDEX IDX_36ABB0A73477C7E0 ON cuenta_corriente (servicio_id_id)');
        $this->addSql('CREATE INDEX IDX_36ABB0A7D3127EC7 ON cuenta_corriente (reserva_hangar_id_id)');
        $this->addSql('CREATE TABLE curso (id INT NOT NULL, alumno_id_id INT NOT NULL, descripcion TEXT NOT NULL, aprobado BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_CA3B40ECD3819735 ON curso (alumno_id_id)');
        $this->addSql('CREATE TABLE gasto (id INT NOT NULL, tesorero_id_id INT NOT NULL, valor INT NOT NULL, descripcion TEXT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_AE43DA149221F5E9 ON gasto (tesorero_id_id)');
        $this->addSql('CREATE TABLE hangar (id INT NOT NULL, descripcion TEXT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE historial_lista_precio (id INT NOT NULL, porcentaje_cambio INT NOT NULL, fecha TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE instructor (id INT NOT NULL, dni VARCHAR(50) NOT NULL, nombre VARCHAR(255) NOT NULL, apellido VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, telefono VARCHAR(255) NOT NULL, domicilio TEXT NOT NULL, ciudad VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE instructor_vuelo (id INT NOT NULL, instructor_id_id INT NOT NULL, vuelo_id_id INT NOT NULL, unidades_pagar INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_64DA0439AD96791B ON instructor_vuelo (instructor_id_id)');
        $this->addSql('CREATE INDEX IDX_64DA0439C580F9FB ON instructor_vuelo (vuelo_id_id)');
        $this->addSql('CREATE TABLE lista_precio (id INT NOT NULL, historial_lista_precio_id_id INT DEFAULT NULL, servicio_id_id INT DEFAULT NULL, producto_id_id INT DEFAULT NULL, precio INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_A392BA6374855384 ON lista_precio (historial_lista_precio_id_id)');
        $this->addSql('CREATE INDEX IDX_A392BA633477C7E0 ON lista_precio (servicio_id_id)');
        $this->addSql('CREATE INDEX IDX_A392BA633F63963D ON lista_precio (producto_id_id)');
        $this->addSql('CREATE TABLE movimiento_cuenta_vuelo (id INT NOT NULL, vuelo_id_id INT NOT NULL, unidades_gastadas INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_27912D5DC580F9FB ON movimiento_cuenta_vuelo (vuelo_id_id)');
        $this->addSql('CREATE TABLE movimiento_stock (id INT NOT NULL, tesorero_id_id INT NOT NULL, producto_id_id INT NOT NULL, cantidad INT NOT NULL, tipo VARCHAR(255) NOT NULL, observaciones TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_4AEEC2D09221F5E9 ON movimiento_stock (tesorero_id_id)');
        $this->addSql('CREATE INDEX IDX_4AEEC2D03F63963D ON movimiento_stock (producto_id_id)');
        $this->addSql('CREATE TABLE nota (id INT NOT NULL, tesorero_id_id INT NOT NULL, descripcion TEXT NOT NULL, fecha_recordatorio DATE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_C8D03E0D9221F5E9 ON nota (tesorero_id_id)');
        $this->addSql('CREATE TABLE piloto (id INT NOT NULL, dni VARCHAR(50) NOT NULL, nombre VARCHAR(255) NOT NULL, apellido VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, telefono VARCHAR(255) NOT NULL, domicilio TEXT NOT NULL, ciudad VARCHAR(255) NOT NULL, fecha_vencimiento_licencia_medica TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, tipo_licencia TEXT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE producto (id INT NOT NULL, descripcion TEXT NOT NULL, estado VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE producto_venta (id INT NOT NULL, producto_id_id INT NOT NULL, venta_id_id INT NOT NULL, cantidad INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_CFC0E63F3F63963D ON producto_venta (producto_id_id)');
        $this->addSql('CREATE INDEX IDX_CFC0E63F9F1AB70D ON producto_venta (venta_id_id)');
        $this->addSql('CREATE TABLE producto_vuelo (id INT NOT NULL, producto_id_id INT NOT NULL, vuelo_id_id INT NOT NULL, cantidad INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_F62FEB1F3F63963D ON producto_vuelo (producto_id_id)');
        $this->addSql('CREATE INDEX IDX_F62FEB1FC580F9FB ON producto_vuelo (vuelo_id_id)');
        $this->addSql('CREATE TABLE reserva (id INT NOT NULL, piloto_id_id INT DEFAULT NULL, socio_id_id INT DEFAULT NULL, fecha TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_188D2E3B2D5D35A3 ON reserva (piloto_id_id)');
        $this->addSql('CREATE INDEX IDX_188D2E3BBFA13376 ON reserva (socio_id_id)');
        $this->addSql('CREATE TABLE reserva_hangar (id INT NOT NULL, reserva_id_id INT NOT NULL, hangar_id_id INT NOT NULL, unidades_gastadas INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_17911C34E83688EE ON reserva_hangar (reserva_id_id)');
        $this->addSql('CREATE INDEX IDX_17911C3410F5FF80 ON reserva_hangar (hangar_id_id)');
        $this->addSql('CREATE TABLE reserva_vuelo (id INT NOT NULL, avion_id_id INT NOT NULL, reserva_id_id INT NOT NULL, duracion DOUBLE PRECISION NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_217AF5CC67B66CF3 ON reserva_vuelo (avion_id_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_217AF5CCE83688EE ON reserva_vuelo (reserva_id_id)');
        $this->addSql('CREATE TABLE servicio (id INT NOT NULL, codigo VARCHAR(255) NOT NULL, descripcion TEXT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE socio (id INT NOT NULL, dni VARCHAR(50) NOT NULL, nombre VARCHAR(255) NOT NULL, apellido VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, telefono VARCHAR(255) NOT NULL, domicilio TEXT NOT NULL, ciudad VARCHAR(255) NOT NULL, fecha_vencimiento_licencia_medica TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, tipo_licencia TEXT NOT NULL, numero_socio TEXT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE tesorero (id INT NOT NULL, nombre VARCHAR(255) NOT NULL, apellido VARCHAR(255) NOT NULL, correo VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE unidades_pago (id INT NOT NULL, servicio_id_id INT NOT NULL, unidad_relativa INT NOT NULL, fecha TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_BE00C5073477C7E0 ON unidades_pago (servicio_id_id)');
        $this->addSql('CREATE TABLE venta (id INT NOT NULL, socio_id_id INT DEFAULT NULL, piloto_id_id INT DEFAULT NULL, tesorero_id_id INT DEFAULT NULL, observaciones TEXT DEFAULT NULL, fecha DATE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_8FE7EE55BFA13376 ON venta (socio_id_id)');
        $this->addSql('CREATE INDEX IDX_8FE7EE552D5D35A3 ON venta (piloto_id_id)');
        $this->addSql('CREATE INDEX IDX_8FE7EE559221F5E9 ON venta (tesorero_id_id)');
        $this->addSql('CREATE TABLE vuelo (id INT NOT NULL, curso_id_id INT DEFAULT NULL, socio_id_id INT DEFAULT NULL, piloto_id_id INT DEFAULT NULL, avion_id_id INT NOT NULL, observaciones TEXT NOT NULL, fecha DATE NOT NULL, es_vuelo_turistico BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_B608E375771B9D4D ON vuelo (curso_id_id)');
        $this->addSql('CREATE INDEX IDX_B608E375BFA13376 ON vuelo (socio_id_id)');
        $this->addSql('CREATE INDEX IDX_B608E3752D5D35A3 ON vuelo (piloto_id_id)');
        $this->addSql('CREATE INDEX IDX_B608E37567B66CF3 ON vuelo (avion_id_id)');
        $this->addSql('CREATE TABLE vuelo_motor (id INT NOT NULL, vuelo_id_id INT NOT NULL, aterrizajes INT NOT NULL, pista_despegue VARCHAR(255) NOT NULL, pista_aterrizaje VARCHAR(255) NOT NULL, horometro_despegue INT NOT NULL, horometro_aterrizaje INT NOT NULL, tipo_vuelo VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_719763ECC580F9FB ON vuelo_motor (vuelo_id_id)');
        $this->addSql('CREATE TABLE vuelo_planeador (id INT NOT NULL, vuelo_id_id INT NOT NULL, tiempo_remolque DOUBLE PRECISION NOT NULL, tiempo_libre DOUBLE PRECISION NOT NULL, tema_vuelo VARCHAR(255) NOT NULL, tiempo_acumulado DOUBLE PRECISION NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_812E14EBC580F9FB ON vuelo_planeador (vuelo_id_id)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGSERIAL NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0 ON messenger_messages (queue_name)');
        $this->addSql('CREATE INDEX IDX_75EA56E0E3BD61CE ON messenger_messages (available_at)');
        $this->addSql('CREATE INDEX IDX_75EA56E016BA31DB ON messenger_messages (delivered_at)');
        $this->addSql('CREATE OR REPLACE FUNCTION notify_messenger_messages() RETURNS TRIGGER AS $$
            BEGIN
                PERFORM pg_notify(\'messenger_messages\', NEW.queue_name::text);
                RETURN NEW;
            END;
        $$ LANGUAGE plpgsql;');
        $this->addSql('DROP TRIGGER IF EXISTS notify_trigger ON messenger_messages;');
        $this->addSql('CREATE TRIGGER notify_trigger AFTER INSERT OR UPDATE ON messenger_messages FOR EACH ROW EXECUTE PROCEDURE notify_messenger_messages();');
        $this->addSql('ALTER TABLE abono ADD CONSTRAINT FK_96A720959221F5E9 FOREIGN KEY (tesorero_id_id) REFERENCES tesorero (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE abono ADD CONSTRAINT FK_96A72095BFA13376 FOREIGN KEY (socio_id_id) REFERENCES socio (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE abono ADD CONSTRAINT FK_96A720952D5D35A3 FOREIGN KEY (piloto_id_id) REFERENCES piloto (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE alumno ADD CONSTRAINT FK_1435D52DDB969FD1 FOREIGN KEY (habilitado_por_instructor_id_id) REFERENCES instructor (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE alumno ADD CONSTRAINT FK_1435D52DE3767AC7 FOREIGN KEY (habilitado_por_tesorero_id_id) REFERENCES tesorero (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE cuenta_corriente ADD CONSTRAINT FK_36ABB0A744C354F3 FOREIGN KEY (movimiento_cuenta_vuelo_id_id) REFERENCES movimiento_cuenta_vuelo (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE cuenta_corriente ADD CONSTRAINT FK_36ABB0A7ED1CD59C FOREIGN KEY (lista_precio_id_id) REFERENCES lista_precio (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE cuenta_corriente ADD CONSTRAINT FK_36ABB0A750343FC1 FOREIGN KEY (abono_id_id) REFERENCES abono (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE cuenta_corriente ADD CONSTRAINT FK_36ABB0A79F1AB70D FOREIGN KEY (venta_id_id) REFERENCES venta (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE cuenta_corriente ADD CONSTRAINT FK_36ABB0A73477C7E0 FOREIGN KEY (servicio_id_id) REFERENCES servicio (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE cuenta_corriente ADD CONSTRAINT FK_36ABB0A7D3127EC7 FOREIGN KEY (reserva_hangar_id_id) REFERENCES reserva_hangar (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE curso ADD CONSTRAINT FK_CA3B40ECD3819735 FOREIGN KEY (alumno_id_id) REFERENCES alumno (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE gasto ADD CONSTRAINT FK_AE43DA149221F5E9 FOREIGN KEY (tesorero_id_id) REFERENCES tesorero (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE instructor_vuelo ADD CONSTRAINT FK_64DA0439AD96791B FOREIGN KEY (instructor_id_id) REFERENCES instructor (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE instructor_vuelo ADD CONSTRAINT FK_64DA0439C580F9FB FOREIGN KEY (vuelo_id_id) REFERENCES vuelo (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE lista_precio ADD CONSTRAINT FK_A392BA6374855384 FOREIGN KEY (historial_lista_precio_id_id) REFERENCES historial_lista_precio (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE lista_precio ADD CONSTRAINT FK_A392BA633477C7E0 FOREIGN KEY (servicio_id_id) REFERENCES servicio (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE lista_precio ADD CONSTRAINT FK_A392BA633F63963D FOREIGN KEY (producto_id_id) REFERENCES producto (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE movimiento_cuenta_vuelo ADD CONSTRAINT FK_27912D5DC580F9FB FOREIGN KEY (vuelo_id_id) REFERENCES vuelo (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE movimiento_stock ADD CONSTRAINT FK_4AEEC2D09221F5E9 FOREIGN KEY (tesorero_id_id) REFERENCES tesorero (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE movimiento_stock ADD CONSTRAINT FK_4AEEC2D03F63963D FOREIGN KEY (producto_id_id) REFERENCES producto (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE nota ADD CONSTRAINT FK_C8D03E0D9221F5E9 FOREIGN KEY (tesorero_id_id) REFERENCES tesorero (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE producto_venta ADD CONSTRAINT FK_CFC0E63F3F63963D FOREIGN KEY (producto_id_id) REFERENCES producto (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE producto_venta ADD CONSTRAINT FK_CFC0E63F9F1AB70D FOREIGN KEY (venta_id_id) REFERENCES venta (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE producto_vuelo ADD CONSTRAINT FK_F62FEB1F3F63963D FOREIGN KEY (producto_id_id) REFERENCES producto (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE producto_vuelo ADD CONSTRAINT FK_F62FEB1FC580F9FB FOREIGN KEY (vuelo_id_id) REFERENCES vuelo (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE reserva ADD CONSTRAINT FK_188D2E3B2D5D35A3 FOREIGN KEY (piloto_id_id) REFERENCES piloto (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE reserva ADD CONSTRAINT FK_188D2E3BBFA13376 FOREIGN KEY (socio_id_id) REFERENCES socio (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE reserva_hangar ADD CONSTRAINT FK_17911C34E83688EE FOREIGN KEY (reserva_id_id) REFERENCES reserva (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE reserva_hangar ADD CONSTRAINT FK_17911C3410F5FF80 FOREIGN KEY (hangar_id_id) REFERENCES hangar (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE reserva_vuelo ADD CONSTRAINT FK_217AF5CC67B66CF3 FOREIGN KEY (avion_id_id) REFERENCES avion (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE reserva_vuelo ADD CONSTRAINT FK_217AF5CCE83688EE FOREIGN KEY (reserva_id_id) REFERENCES reserva (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE unidades_pago ADD CONSTRAINT FK_BE00C5073477C7E0 FOREIGN KEY (servicio_id_id) REFERENCES servicio (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE venta ADD CONSTRAINT FK_8FE7EE55BFA13376 FOREIGN KEY (socio_id_id) REFERENCES socio (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE venta ADD CONSTRAINT FK_8FE7EE552D5D35A3 FOREIGN KEY (piloto_id_id) REFERENCES piloto (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE venta ADD CONSTRAINT FK_8FE7EE559221F5E9 FOREIGN KEY (tesorero_id_id) REFERENCES tesorero (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE vuelo ADD CONSTRAINT FK_B608E375771B9D4D FOREIGN KEY (curso_id_id) REFERENCES curso (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE vuelo ADD CONSTRAINT FK_B608E375BFA13376 FOREIGN KEY (socio_id_id) REFERENCES socio (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE vuelo ADD CONSTRAINT FK_B608E3752D5D35A3 FOREIGN KEY (piloto_id_id) REFERENCES piloto (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE vuelo ADD CONSTRAINT FK_B608E37567B66CF3 FOREIGN KEY (avion_id_id) REFERENCES avion (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE vuelo_motor ADD CONSTRAINT FK_719763ECC580F9FB FOREIGN KEY (vuelo_id_id) REFERENCES vuelo (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE vuelo_planeador ADD CONSTRAINT FK_812E14EBC580F9FB FOREIGN KEY (vuelo_id_id) REFERENCES vuelo (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('DROP SEQUENCE abono_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE alumno_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE avion_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE cuenta_corriente_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE curso_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE gasto_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE hangar_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE historial_lista_precio_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE instructor_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE instructor_vuelo_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE lista_precio_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE movimiento_cuenta_vuelo_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE movimiento_stock_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE nota_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE piloto_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE producto_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE producto_venta_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE producto_vuelo_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE reserva_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE reserva_hangar_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE reserva_vuelo_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE servicio_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE socio_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE tesorero_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE unidades_pago_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE venta_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE vuelo_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE vuelo_motor_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE vuelo_planeador_id_seq CASCADE');
        $this->addSql('ALTER TABLE abono DROP CONSTRAINT FK_96A720959221F5E9');
        $this->addSql('ALTER TABLE abono DROP CONSTRAINT FK_96A72095BFA13376');
        $this->addSql('ALTER TABLE abono DROP CONSTRAINT FK_96A720952D5D35A3');
        $this->addSql('ALTER TABLE alumno DROP CONSTRAINT FK_1435D52DDB969FD1');
        $this->addSql('ALTER TABLE alumno DROP CONSTRAINT FK_1435D52DE3767AC7');
        $this->addSql('ALTER TABLE cuenta_corriente DROP CONSTRAINT FK_36ABB0A744C354F3');
        $this->addSql('ALTER TABLE cuenta_corriente DROP CONSTRAINT FK_36ABB0A7ED1CD59C');
        $this->addSql('ALTER TABLE cuenta_corriente DROP CONSTRAINT FK_36ABB0A750343FC1');
        $this->addSql('ALTER TABLE cuenta_corriente DROP CONSTRAINT FK_36ABB0A79F1AB70D');
        $this->addSql('ALTER TABLE cuenta_corriente DROP CONSTRAINT FK_36ABB0A73477C7E0');
        $this->addSql('ALTER TABLE cuenta_corriente DROP CONSTRAINT FK_36ABB0A7D3127EC7');
        $this->addSql('ALTER TABLE curso DROP CONSTRAINT FK_CA3B40ECD3819735');
        $this->addSql('ALTER TABLE gasto DROP CONSTRAINT FK_AE43DA149221F5E9');
        $this->addSql('ALTER TABLE instructor_vuelo DROP CONSTRAINT FK_64DA0439AD96791B');
        $this->addSql('ALTER TABLE instructor_vuelo DROP CONSTRAINT FK_64DA0439C580F9FB');
        $this->addSql('ALTER TABLE lista_precio DROP CONSTRAINT FK_A392BA6374855384');
        $this->addSql('ALTER TABLE lista_precio DROP CONSTRAINT FK_A392BA633477C7E0');
        $this->addSql('ALTER TABLE lista_precio DROP CONSTRAINT FK_A392BA633F63963D');
        $this->addSql('ALTER TABLE movimiento_cuenta_vuelo DROP CONSTRAINT FK_27912D5DC580F9FB');
        $this->addSql('ALTER TABLE movimiento_stock DROP CONSTRAINT FK_4AEEC2D09221F5E9');
        $this->addSql('ALTER TABLE movimiento_stock DROP CONSTRAINT FK_4AEEC2D03F63963D');
        $this->addSql('ALTER TABLE nota DROP CONSTRAINT FK_C8D03E0D9221F5E9');
        $this->addSql('ALTER TABLE producto_venta DROP CONSTRAINT FK_CFC0E63F3F63963D');
        $this->addSql('ALTER TABLE producto_venta DROP CONSTRAINT FK_CFC0E63F9F1AB70D');
        $this->addSql('ALTER TABLE producto_vuelo DROP CONSTRAINT FK_F62FEB1F3F63963D');
        $this->addSql('ALTER TABLE producto_vuelo DROP CONSTRAINT FK_F62FEB1FC580F9FB');
        $this->addSql('ALTER TABLE reserva DROP CONSTRAINT FK_188D2E3B2D5D35A3');
        $this->addSql('ALTER TABLE reserva DROP CONSTRAINT FK_188D2E3BBFA13376');
        $this->addSql('ALTER TABLE reserva_hangar DROP CONSTRAINT FK_17911C34E83688EE');
        $this->addSql('ALTER TABLE reserva_hangar DROP CONSTRAINT FK_17911C3410F5FF80');
        $this->addSql('ALTER TABLE reserva_vuelo DROP CONSTRAINT FK_217AF5CC67B66CF3');
        $this->addSql('ALTER TABLE reserva_vuelo DROP CONSTRAINT FK_217AF5CCE83688EE');
        $this->addSql('ALTER TABLE unidades_pago DROP CONSTRAINT FK_BE00C5073477C7E0');
        $this->addSql('ALTER TABLE venta DROP CONSTRAINT FK_8FE7EE55BFA13376');
        $this->addSql('ALTER TABLE venta DROP CONSTRAINT FK_8FE7EE552D5D35A3');
        $this->addSql('ALTER TABLE venta DROP CONSTRAINT FK_8FE7EE559221F5E9');
        $this->addSql('ALTER TABLE vuelo DROP CONSTRAINT FK_B608E375771B9D4D');
        $this->addSql('ALTER TABLE vuelo DROP CONSTRAINT FK_B608E375BFA13376');
        $this->addSql('ALTER TABLE vuelo DROP CONSTRAINT FK_B608E3752D5D35A3');
        $this->addSql('ALTER TABLE vuelo DROP CONSTRAINT FK_B608E37567B66CF3');
        $this->addSql('ALTER TABLE vuelo_motor DROP CONSTRAINT FK_719763ECC580F9FB');
        $this->addSql('ALTER TABLE vuelo_planeador DROP CONSTRAINT FK_812E14EBC580F9FB');
        $this->addSql('DROP TABLE abono');
        $this->addSql('DROP TABLE alumno');
        $this->addSql('DROP TABLE avion');
        $this->addSql('DROP TABLE cuenta_corriente');
        $this->addSql('DROP TABLE curso');
        $this->addSql('DROP TABLE gasto');
        $this->addSql('DROP TABLE hangar');
        $this->addSql('DROP TABLE historial_lista_precio');
        $this->addSql('DROP TABLE instructor');
        $this->addSql('DROP TABLE instructor_vuelo');
        $this->addSql('DROP TABLE lista_precio');
        $this->addSql('DROP TABLE movimiento_cuenta_vuelo');
        $this->addSql('DROP TABLE movimiento_stock');
        $this->addSql('DROP TABLE nota');
        $this->addSql('DROP TABLE piloto');
        $this->addSql('DROP TABLE producto');
        $this->addSql('DROP TABLE producto_venta');
        $this->addSql('DROP TABLE producto_vuelo');
        $this->addSql('DROP TABLE reserva');
        $this->addSql('DROP TABLE reserva_hangar');
        $this->addSql('DROP TABLE reserva_vuelo');
        $this->addSql('DROP TABLE servicio');
        $this->addSql('DROP TABLE socio');
        $this->addSql('DROP TABLE tesorero');
        $this->addSql('DROP TABLE unidades_pago');
        $this->addSql('DROP TABLE venta');
        $this->addSql('DROP TABLE vuelo');
        $this->addSql('DROP TABLE vuelo_motor');
        $this->addSql('DROP TABLE vuelo_planeador');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
